import Head from "next/head";
import {useState} from "react";
import Image from "next/image";
import "@/styles/home.css";
import { Nav } from "rsuite";
import { Grid, Row, Col } from "rsuite";
import { FlexboxGrid } from "rsuite";
import { Accordion } from 'rsuite';
import { AvatarGroup, Avatar } from "rsuite";
import { Divider } from "rsuite";
import GlobalIcon from "@rsuite/icons/Global";
import StarIcon from "@rsuite/icons/Star";
import SortUpIcon from "@rsuite/icons/SortUp";
import TrendIcon from "@rsuite/icons/Trend";
import GridIcon from "@rsuite/icons/Grid";
import CopyIcon from "@rsuite/icons/Copy";
import ShieldIcon from "@rsuite/icons/Shield";
import MenuIcon from '@rsuite/icons/Menu';

export default function Home() {
  const users = [
    { avatar: "https://i.pravatar.cc/150?u=2", name: "Tom Doe" },
    { avatar: "https://i.pravatar.cc/150?u=6", name: "Mike Doe" },
    { avatar: "https://i.pravatar.cc/150?u=7", name: "Jane Doe" },
  ];

  return (
    <>
      <Head>
        <title>Ascone</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      <div className="header">
        <div className="brand">
          <div>
          <h1 className="brand-title">Ascone</h1>
          </div>
          <div>
          <MenuIcon className="menu-icon"/>
          </div>
        </div>
        <div className="nav-btns"
          style={{
            display: "flex",
            justifyContent: "space-between",
            alignItems: "center",
            width: "950px",
          }}
        >
          <Nav className="nav-items">
            <Nav.Item href="#features">Features</Nav.Item>
            <Nav.Item href="#values">Values</Nav.Item>
            <Nav.Item href="#numbers">Numbers</Nav.Item>
            <Nav.Item>FAQ</Nav.Item>
          </Nav>
          <div className="btns" >
            <button className="login">Login</button>
            <button className="signUp">Sign Up</button>
          </div>
        </div>
      </div>

      <div className="hero-section">
        <div>
          <p className="act">Try it now!</p>
          <h2 className="hero-title">
            Change the way
             you use your <i>money</i>
          </h2>
          <p className="hero-text">
            From your everyday spending, to planning for your future with
            savings and investments, Aston capital helps you get more from
            your money.
          </p>
          <div className="btn-container">
            <button className="hero-btn">Get Started Now</button>
          </div>
        </div>
        <div className="hero-cards">
          <div className="card card--1">
            <Image
              src="/img/card1.png"
              alt=""
              width={270}
              height={260}
              className="card1"
            />
          </div>
          <div className="card card--2">
            <div className="card2-items">
              <p style={{ marginLeft: 150, fontSize: "60px" }}>56+</p>
              <p style={{ fontSize: "24px", marginLeft: 30 }}>Currencies</p>
            </div>
            <div>
              <GlobalIcon
                style={{ fontSize: "64px", marginLeft: 180, fontWeight: 200 }}
              />
            </div>
          </div>
          <div className="card card--3">
            <StarIcon style={{ fontSize: "44px", marginTop: 10 }} />
            <StarIcon style={{ fontSize: "44px", marginTop: 10 }} />
            <div
              className="card3-items
            "
            >
              <p style={{ fontSize: "24px", fontWeight: 500, marginLeft: 100 }}>
                Users Active
              </p>
              <AvatarGroup stack style={{ marginLeft: 40, marginTop: 50 }}>
                {users.map((user) => (
                  <Avatar
                    bordered
                    circle
                    key={user.name}
                    src={user.avatar}
                    size="md"
                  />
                ))}
                <Avatar
                  bordered
                  circle
                  style={{ background: "#48483e" }}
                ></Avatar>
              </AvatarGroup>
            </div>
          </div>
          <div className="card card--4">
            <div className="card4-items">
              <p
                style={{
                  fontSize: "36px",
                  letterSpacing: "",
                  color: "#fff",
                  lineHeight: 1.2,
                }}
              >
                $196,000
              </p>
              <SortUpIcon style={{ stroke: "#fff", fontSize: "32px" }} />
            </div>
            <TrendIcon
              style={{
                fontSize: "48px",
                color: "#fff",
                marginTop: 50,
                width: "90px",
              }}
            />
            <p
              style={{
                color: "#fff",
                fontSize: "24px",
                marginTop: 50,
                marginLeft: 150,
              }}
            >
              Savings
            </p>
          </div>
        </div>
      </div>
      <section id="features">
        <div className="brand-features">
          <h3 className="features-title">FEATURES</h3>
          <h2 className="features-text">
            One app for all your money things
          </h2>
          <p className="features-text2">
            Remove all the friction that stands in the way of your money
            goals
          </p>
        </div>
        <div className="features-feature">
          <div className="feature-1">
            <h3>Grow savings faster</h3>
            <p
              style={{
                fontSize: "30px",
                color: "#FFFFE2",
                marginLeft: "128px",
                fontWeight: 500,
              }}
            >
              $12,000
            </p>
            <TrendIcon
              style={{ fontSize: "200px", color: "#FFFFE2", marginTop: "64px" }}
            />
          </div>
          <div className="feature-2">
            <h3>Send across the globe </h3>
            <div className="feat2-ornaments">
              <Image src="/img/dollars2.png" alt="" height={250} width={150} />
              <GlobalIcon className="globe"
                style={{
                  fontSize: "100px",
                  color: "#161612",
                  alignSelf: "center",
                }}
              />
              <Image className="contry-flg"
                src="/img/countries.png"
                alt=""
                height={50}
                width={110}
                style={{ alignSelf: "flex-end", marginRight: 100 }}
              />
            </div>
          </div>
        </div>
      </section>
      <section id="values">
        <div className="values-txt">
          <div className="values-intro">
            <h3>VALUES</h3>
            <h2>Make your spend, Well-spent</h2>
          </div>
          <div>
            <p className="values-intro2">
              Manages a diversified group of specialized private credit brands
              with efficient tech-enabled processes
            </p>
          </div>
        </div>
        <div className="brand-vals">
          <div className="val-1">
            <GridIcon style={{ fontSize: "52px"}} />
            <div className="val1-txt">
              <h5 style={{ fontWeight: 600 }}>Transparency</h5>
              <p>
                A departure from the industry norm of ambiguity, Montfort, as a
                public and finest company
              </p>
            </div>
            <button className="arr-btn">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={2.5}
                stroke="currentColor"
                className="size-6"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25"
                />
              </svg>
            </button>
          </div>
          <div className="val-2">
            <CopyIcon style={{ fontSize: "52px" }} />
            <div className="val2-txt">
              <h5 style={{ fontWeight: 600 }}>Creative Expansion</h5>
              <p>
                Ascone proprietary fintech platform helps our subsidiaries
                locate and manage investments.
              </p>
            </div>
            <button className="arr-btn">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={2.5}
                stroke="currentColor"
                className="size-6"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25"
                />
              </svg>
            </button>
          </div>
          <div className="val-3">
            <ShieldIcon style={{ fontSize: "52px" }} />
            <div className="val3-txt">
              <h5 style={{ fontWeight: 600 }}>Private Credit Investments</h5>
              <p>
                We provide access to unique private credit investments; a rare
                but valuable part of a sound investment portfolio.
              </p>
            </div>
            <button className="arr-btn">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                fill="none"
                viewBox="0 0 24 24"
                strokeWidth={2.5}
                stroke="currentColor"
                className="size-6"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  d="m4.5 19.5 15-15m0 0H8.25m11.25 0v11.25"
                />
              </svg>
            </button>
          </div>
        </div>
      </section>
      <section id="numbers">
        <div className="numbers-container">
          <div className="numbers-item1">
            <div>
              <p
                style={{
                  fontSize: "120px",
                  lineHeight: 1.2,
                  letterSpacing: "-1.2px",
                }}
              >
                $14B
              </p>
              <p
                style={{ fontSize: "24px", fontWeight: 500, lineHeight: 1.25 }}
              >
                Funds and syndicates
              </p>
            </div>
            <div>
              <p
                style={{
                  fontSize: "120px",
                  lineHeight: 1.2,
                  letterSpacing: "-1.2px",
                }}
              >
                23k+
              </p>
              <p
                style={{ fontSize: "24px", fontWeight: 500, lineHeight: 1.25 }}
              >
                Raised by active startups
              </p>
            </div>
          </div>
          <div className="numbers-item3">
            <h3 style={{ textTransform: "uppercase", fontWeight: 400 }}>
              Numbers
            </h3>
            <h2 style={{ fontSize: "40px", fontWeight: 500, lineHeight: 1.2 }}>
              Market and build the solutions
            </h2>
          </div>
        </div>
      </section>
      <section id="faq">
        <div className="faq-container">
          <Grid fluid>
            <Row>
              <Col xs={12}>
                <div>
                  <h3 style={{ textTransform: "uppercase", fontWeight: 700 }}>
                    Faq
                  </h3>
                  <h2 style={{ fontSize: "60px", fontWeight: 600 }}>
                    Frequently asked questions?
                  </h2>
                </div>
              </Col>
              <Col xs={12}>
                <div className="faqs">
                  <Accordion>
                  <Accordion.Panel header="How to do a bank transfer" >   
                    <p className="faq-text">
                    Choosing between different options such as online banking, mobile apps, in-person transfers at a bank branch, or using a bank ATM.
                    </p>
                  </Accordion.Panel> 
                  <Accordion.Panel header="What is the scheduled payments feature?" >   
                    <p className="faq-text">
                    The scheduled payments feature allows you to manage all of your subscriptions or recurring payments in one place. This way, you can view details for every payment, which include the amount, frequency, payment dates etc.
                    </p>
                  </Accordion.Panel> 
                  <Accordion.Panel header="How can I reactivate a terminated card?" >   
                    <p className="faq-text">
                    Depending on the reason for termination, the bank may have specific steps for reactivation, such as signing new terms, updating details, or reissuing a new card.
                    </p>
                  </Accordion.Panel> 
                  <Accordion.Panel header="How about with a refund?" >   
                    <p className="faq-text">
                    Ensure that the product or service you want a refund for meets the refund criteria set by the company. Refunds can take several days or even weeks to reflect in your account, depending on the payment method and the company’s processing times.
                    </p>
                  </Accordion.Panel> 
                  <Accordion.Panel header="How can I add money to my account?" >   
                    <p className="faq-text">
                    Describing the various ways to add funds, such as bank transfers, cash deposits, using a debit or credit card, or mobile check deposits.
                    </p>
                  </Accordion.Panel> 
                  </Accordion>
                  <Divider />
                  </div>
              </Col>
            </Row>
          </Grid>
        </div>
      </section>
      <div className="cta-container">
        <div className="cta">
          <div className="cta-txt">
            <h3
              style={{
                fontSize: "72px",
                letterSpacing: -0.72,
                fontWeight: 500,
                width: "750px",
              }}
            >
              Change the way you use your{" "}
              <span
                style={{
                  fontStyle: "italic",
                  fontWeight: 400,
                  letterSpacing: -0.74,
                  fontSize: "74px",
                }}
              >
                money
              </span>
            </h3>
            <p style={{ fontSize: "20px", maxWidth: "400px" }}>
              Join over million people who choose Aston Capital for fast and
              secure future banking.
            </p>
            <button className="cta-btn">Get Started Now</button>
          </div>
          <div className="cta-ornaments">
            <div className="ornament1">
              <StarIcon style={{ width: 160, height: 160 }} />
              <StarIcon style={{ width: 160, height: 160 }} />
            </div>
            <div className="ornament2">
              <Image
                className="cta-img"
                src="/img/dollars.jpg"
                alt="dollar notes"
                height={200}
                width={200}
              />
            </div>
          </div>
        </div>
      </div>
      <div className="footer-container">
        <div
          className="footer-top"
          style={{
            marginBottom: "50px",
            display: "flex",
            justifyContent: "space-between",
          }}
        >
          <div className="grid-links">
            <Grid fluid>
              <Row gutter={30}>
                <Col xs={6}>
                  <h4>Account</h4>
                  <div className="links-box">
                    <a className="footer-links" href="#">
                      Saving
                    </a>
                    <a className="footer-links" href="#">
                      Join Accounts
                    </a>
                    <a className="footer-links" href="#">
                      Crypto
                    </a>
                    <a className="footer-links" href="#">
                      Freelance
                    </a>
                    <a className="footer-links" href="#">
                      Commodities
                    </a>
                  </div>
                </Col>
                <Col xs={6}>
                  <h4>Help</h4>
                  <div className="links-box">
                    <a className="footer-links" href="#">
                      Customer Help
                    </a>
                    <a className="footer-links" href="#">
                      Community
                    </a>
                    <a className="footer-links" href="#">
                      Blog
                    </a>
                  </div>
                </Col>
                <Col xs={6}>
                  <h4>Finance</h4>
                  <div className="links-box">
                    <a className="footer-links" href="#">
                      Cards
                    </a>
                    <a className="footer-links" href="#">
                      Linked Accounts
                    </a>
                    <a className="footer-links" href="#">
                      Payment
                    </a>
                    <a className="footer-links" href="#">
                      Freelance
                    </a>
                    <a className="footer-links" href="#">
                      Commodities
                    </a>
                  </div>
                </Col>
                <Col xs={6}>
                  <h4>Company</h4>
                  <div className="links-box">
                    <a className="footer-links" href="#">
                      About Us
                    </a>
                    <a className="footer-links" href="#">
                      Contact
                    </a>
                    <a className="footer-links" href="#">
                      Sustainability
                    </a>
                    <a className="footer-links" href="#">
                      Career
                    </a>
                  </div>
                </Col>
              </Row>
            </Grid>
          </div>
          <div>
            <h1 style={{ fontSize: "40px" }}>Aston Capital</h1>
          </div>
        </div>
        <Divider style={{ color: "#252a1c" }} />
        <div
          className="footer-bottom"
          style={{ marginBottom: "50px", marginTop: "50px" }}
        >
          <FlexboxGrid justify="space-between">
            <FlexboxGrid.Item>
              <div>
                <p style={{ fontWeight: 500 }}>
                  &#169; Aston Capital Ltd. 2025
                </p>
              </div>
            </FlexboxGrid.Item>
            <FlexboxGrid.Item>
              <div className="policy-links">
                <a className="footer-links" href="#">
                  Privacy Policy
                </a>
                <a className="footer-links" href="#">
                  Terms of Use
                </a>
                <a className="footer-links" href="#">
                  Disclosure
                </a>
              </div>
            </FlexboxGrid.Item>
          </FlexboxGrid>
        </div>
      </div>
    </>
  );
}
